# ---------------------------------------------------
# 配置: 数据集生成 (版本 1)
# ---------------------------------------------------

# 输出目录，所有生成的数据都将保存在这里
output_path: "./data/synthetic_dataset_v1"

# 要生成的样本总数
num_samples: 50000

# 生成图像的方形分辨率（像素）
image_resolution: 256